// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYgl5vTkzPNGFzt0lqvFlTnrj7pYMZmGo',
    appId: '1:708837297818:web:8b7aefd103d4bb6e219923',
    messagingSenderId: '708837297818',
    projectId: 'fir-project-3540a',
    authDomain: 'fir-project-3540a.firebaseapp.com',
    storageBucket: 'fir-project-3540a.appspot.com',
    measurementId: 'G-D6H0T07GMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbSzNbwk4qR-s0riw1mF8QTVSLYmpqkLc',
    appId: '1:708837297818:android:cf496a8d40bebc22219923',
    messagingSenderId: '708837297818',
    projectId: 'fir-project-3540a',
    storageBucket: 'fir-project-3540a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPxjPpZAmkZM1R3J9sRCst95rR3qP9oyo',
    appId: '1:708837297818:ios:526654e9eee2a391219923',
    messagingSenderId: '708837297818',
    projectId: 'fir-project-3540a',
    storageBucket: 'fir-project-3540a.appspot.com',
    iosBundleId: 'com.example.pushNotificationWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYgl5vTkzPNGFzt0lqvFlTnrj7pYMZmGo',
    appId: '1:708837297818:web:a8e825f77e062048219923',
    messagingSenderId: '708837297818',
    projectId: 'fir-project-3540a',
    authDomain: 'fir-project-3540a.firebaseapp.com',
    storageBucket: 'fir-project-3540a.appspot.com',
    measurementId: 'G-QN50WWZHJY',
  );
}
